from langchain_openai import OpenAIEmbeddings
from dotenv import load_dotenv
from sklearn.metrics.pairwise import cosine_similarity
load_dotenv()

documents = [

"""The Revolt of 1857 was one of the earliest major uprisings against British rule in India. It began as a mutiny of Indian soldiers in the British East India Company's army but quickly spread across northern and central India. Key centers of the revolt included Meerut, Delhi, Kanpur, and Lucknow. Leaders such as Rani Lakshmibai of Jhansi, Bahadur Shah Zafar, Tantia Tope, and Nana Sahib became prominent figures in the resistance. The revolt was fueled by political annexations, economic exploitation, military grievances, and social and religious concerns. Although the uprising was eventually suppressed by the British, it marked a turning point in Indian history. After 1858, the British Crown took direct control of India from the East India Company. The revolt is remembered as India’s First War of Independence and laid the foundation for organized national movements in the decades that followed.""",

"""The formation of the Indian National Congress in 1885 marked the beginning of a structured political movement in India. Founded by Allan Octavian Hume along with Indian leaders such as Dadabhai Naoroji and Surendranath Banerjee, the Congress initially aimed to create a platform for dialogue between Indians and the British government. Early leaders, known as moderates, sought reforms through petitions and constitutional methods. Over time, the organization evolved into the leading force of the Indian independence movement. It played a crucial role in mobilizing people across regions, religions, and languages. The Congress later adopted more assertive strategies under leaders like Bal Gangadhar Tilak and eventually Mahatma Gandhi. The formation of this organization provided a unified political voice to Indians and helped transform scattered resistance into a nationwide struggle for self-rule.""",

"""The Partition of Bengal in 1905 was announced by Lord Curzon, the Viceroy of India, under the pretext of administrative convenience. The province was divided into Eastern Bengal and Assam, and Western Bengal. However, many Indians believed the decision was intended to divide Hindus and Muslims and weaken the growing nationalist movement. The partition triggered widespread protests, boycotts of British goods, and the launch of the Swadeshi Movement. Leaders such as Bipin Chandra Pal and Lala Lajpat Rai encouraged the promotion of indigenous industries and national education. The agitation marked the rise of extremist leaders in Indian politics and deepened political awareness among the masses. Due to sustained resistance, the British government annulled the partition in 1911. The episode demonstrated the power of organized public protest and significantly strengthened the freedom movement.""",

"""The Non-Cooperation Movement was launched in 1920 under the leadership of Mahatma Gandhi. It was initiated in response to the Jallianwala Bagh massacre and the repressive Rowlatt Act. The movement urged Indians to withdraw cooperation from British institutions by boycotting government schools, courts, titles, and foreign goods. It also promoted khadi and self-reliance. The movement gained widespread support across urban and rural areas, uniting people from diverse backgrounds. However, in 1922, following the violent Chauri Chaura incident where protestors set a police station on fire, Gandhi called off the movement. Although it did not achieve immediate independence, the Non-Cooperation Movement transformed the Indian National Congress into a mass organization and established Gandhi as the central leader of the freedom struggle.""",

"""The Civil Disobedience Movement began in 1930 with the historic Salt March led by Mahatma Gandhi. The British government had imposed a tax on salt, an essential commodity used by all Indians. Gandhi marched from Sabarmati Ashram to Dandi, covering about 240 miles, to symbolically break the salt law by producing salt from seawater. This act inspired nationwide defiance against colonial laws. People refused to pay taxes, boycotted British goods, and organized protests. The movement saw participation from women, students, and peasants. British authorities responded with mass arrests, including that of Gandhi. The movement drew international attention to India’s demand for independence and highlighted the power of nonviolent resistance. Though it did not immediately end British rule, it significantly intensified the struggle for freedom.""",

"""The Quit India Movement was launched in August 1942 during World War II. Led by Mahatma Gandhi, the movement demanded an immediate end to British rule in India. The slogan 'Do or Die' became its rallying cry. The British government responded swiftly by arresting most Congress leaders, including Gandhi and Jawaharlal Nehru. Despite the leadership being imprisoned, protests erupted across the country. Railway tracks were uprooted, communication lines were disrupted, and parallel governments were formed in some regions. The movement demonstrated the depth of Indian resolve for independence. Although it was suppressed with force, it made it clear that British rule could not continue indefinitely. The Quit India Movement is considered one of the final mass movements that paved the way for independence in 1947.""",

"""The Jallianwala Bagh massacre occurred on April 13, 1919, in Amritsar. Thousands of unarmed Indians had gathered peacefully to protest against the Rowlatt Act. General Reginald Dyer ordered troops to fire on the crowd without warning. The firing continued for several minutes, resulting in hundreds of deaths and injuries. The massacre shocked the nation and exposed the brutality of British rule. It led to widespread outrage and intensified the demand for independence. Rabindranath Tagore renounced his knighthood in protest. The incident deeply influenced Mahatma Gandhi and strengthened his resolve to pursue nonviolent resistance. Jallianwala Bagh became a symbol of colonial oppression and a turning point in India’s freedom struggle.""",

"""India gained independence from British rule on August 15, 1947. The struggle for freedom had spanned decades and involved countless sacrifices. Leaders such as Mahatma Gandhi, Jawaharlal Nehru, Sardar Patel, and Subhas Chandra Bose played significant roles in mobilizing the masses. However, independence came with the partition of India into two separate nations: India and Pakistan. The partition led to massive communal violence, displacement, and loss of life. Millions of people migrated across newly drawn borders. Despite the challenges, India emerged as a sovereign democratic nation. The adoption of the Constitution in 1950 established India as a republic. Independence marked the beginning of a new chapter in the nation’s history.""",

"""The adoption of the Indian Constitution on January 26, 1950, marked the establishment of India as a republic. The Constitution was drafted by the Constituent Assembly under the chairmanship of Dr. B. R. Ambedkar. It is one of the longest written constitutions in the world and provides a framework for governance. It guarantees fundamental rights, directive principles, and a federal structure with a strong central government. The Constitution embodies the ideals of justice, liberty, equality, and fraternity. It abolished untouchability and ensured universal adult franchise. The day January 26 is celebrated annually as Republic Day. The adoption of the Constitution laid the foundation for India’s democratic system and rule of law.""",

"""The Green Revolution in the 1960s transformed Indian agriculture and made the country self-sufficient in food grains. It involved the introduction of high-yielding variety seeds, chemical fertilizers, irrigation expansion, and modern farming techniques. Scientists like M. S. Swaminathan played a key role in implementing these agricultural reforms. Punjab, Haryana, and western Uttar Pradesh became major beneficiaries of increased wheat and rice production. The movement helped India overcome food shortages and reduce dependence on imports. However, it also led to environmental concerns such as soil degradation and groundwater depletion. The Green Revolution marked a significant economic and technological shift in independent India and strengthened the country’s food security.""",

]

embedding_model = OpenAIEmbeddings(model="text-embedding-3-large", dimensions=256)
input_query = "Whivh revolution was responsible for making India self-sufficient in food grains?"

document_vectors = embedding_model.embed_documents(documents)
query_vector = embedding_model.embed_query(input_query)

similarity_scores = cosine_similarity([query_vector], document_vectors)[0]

sorted_similarity_scores = sorted(list(enumerate(similarity_scores)), key=lambda x: x[1], reverse=True)
max_similiarity_index, max_similiarity_score = sorted_similarity_scores[0]
print(documents[max_similiarity_index])